// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xnXye_bngFET6vDOu3OcG2ozOisB_6E',
    appId: '1:692458225679:web:35be84d8813e55ce2f237a',
    messagingSenderId: '692458225679',
    projectId: 'bookinghabit',
    authDomain: 'bookinghabit.firebaseapp.com',
    storageBucket: 'bookinghabit.appspot.com',
    measurementId: 'G-SHQH7X2TN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpvBiefMxNFgaMGnWKE7LxYCGzKj1yiA',
    appId: '1:692458225679:android:1bba2af9ec9a904a2f237a',
    messagingSenderId: '692458225679',
    projectId: 'bookinghabit',
    storageBucket: 'bookinghabit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilDJQAH4cHXWiLr57EUuQTkca5OOKRWA',
    appId: '1:692458225679:ios:ed3b40742b4a2cfd2f237a',
    messagingSenderId: '692458225679',
    projectId: 'bookinghabit',
    storageBucket: 'bookinghabit.appspot.com',
    androidClientId: '692458225679-n8qep5hnn6msds8jgus5qrgtup5p15vr.apps.googleusercontent.com',
    iosClientId: '692458225679-3ri4tnuub89hrur4kgi1iqdjvmno9sab.apps.googleusercontent.com',
    iosBundleId: 'com.chplatform.bookinghabit',
  );
}
